apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-app
spec:
    replicas: 3
    selector:
        matchLabels:
            app: nginx-app

    template:
        metadata:
            labels:
                app: nginx-app
        spec:
            containers:
            - name: nginx-app
              image: nginx:1.17-alpine
              ports:
              - containerPort: 80
              volumeMounts:
              - mountPath: /usr/share/nginx/html
                readOnly: true
                name: nginx-conf
            
            volumes:
            - name: nginx-conf
              configMap:
                name: nginx-conf
                items:
                  - key: nginx.index
                    path: index.html
                